_BASE_: "Base-DiffusionDet.yaml"
MODEL:
  WEIGHTS: "checkpoints/swin_base_patch4_window7_224_22k.pth"
  BACKBONE:
    NAME: build_swintransformer_fpn_backbone
  SWIN:
    SIZE: B-22k
  FPN:
    IN_FEATURES: ["swin0", "swin1", "swin2", "swin3" ]
  DiffusionDet:
    NUM_PROPOSALS: 500
    NUM_CLASSES: 4  # 
DATASETS:
  TRAIN: ("dentex_disease_train",)
  TEST:  ("dentex_disease_val",)